I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script2_5.rpy", line 46, in script
    en "ไม่น่าเชื่อว่ารุ่นพี่จะจำชื่อคนที่ไม่มีความสามารถอย่างผมได้นะครับ"
Exception: Sayer 'en' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script2_5.rpy", line 46, in script
    en "ไม่น่าเชื่อว่ารุ่นพี่จะจำชื่อคนที่ไม่มีความสามารถอย่างผมได้นะครับ"
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'en' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Cafe_au_lait 1.0
Mon Apr  3 02:07:47 2023
