I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script7_2.rpy", line 119, in script
    return q7_3
  File "game/script7_2.rpy", line 119, in <module>
    return q7_3
NameError: name 'q7_3' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script7_2.rpy", line 119, in script
    return q7_3
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 1768, in execute
    renpy.store._return = renpy.python.py_eval(self.expression)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script7_2.rpy", line 119, in <module>
    return q7_3
NameError: name 'q7_3' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Cafe_au_lait 1.0
Sat Jun 17 18:47:26 2023
