I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script3_2.rpy", line 24, in script
    "บางทีมันอาจจะเกี่ยวกับเรื่องที่ทำให้เธอเครียดเมื่อวันก่อนก็ได้ ถึงผมไม่รู้ก็เถอะว่ามันคือเรื่องอะไรก็ตาม และผมก็ไม่แน่ใจว่าตัวเองมีสิทธิเข้าไปยุ่งด้วยหรือเปล่า"
  File "game/screens.rpy", line 365, in execute
    screen save():
  File "game/screens.rpy", line 365, in execute
    screen save():
  File "game/screens.rpy", line 367, in execute
    fixed:
  File "game/screens.rpy", line 419, in execute
    grid gui.file_slot_cols gui.file_slot_rows:
  File "game/screens.rpy", line 429, in execute
    for i in range(gui.file_slot_cols * gui.file_slot_rows):
  File "game/screens.rpy", line 433, in execute
    button:
  File "game/screens.rpy", line 433, in keywords
    button:
  File "game/screens.rpy", line 434, in <module>
    action FileSave(slot,Confirm = False)
TypeError: __init__() got an unexpected keyword argument 'Confirm'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script3_2.rpy", line 24, in script
    "บางทีมันอาจจะเกี่ยวกับเรื่องที่ทำให้เธอเครียดเมื่อวันก่อนก็ได้ ถึงผมไม่รู้ก็เถอะว่ามันคือเรื่องอะไรก็ตาม และผมก็ไม่แน่ใจว่าตัวเองมีสิทธิเข้าไปยุ่งด้วยหรือเปล่า"
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\character.py", line 927, in do_display
    display_say(who,
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\character.py", line 666, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 3810, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\screen.py", line 451, in visit_all
    callback(self)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\core.py", line 3810, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\screen.py", line 462, in per_interact
    self.update()
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\display\screen.py", line 653, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 365, in execute
    screen save():
  File "game/screens.rpy", line 365, in execute
    screen save():
  File "game/screens.rpy", line 367, in execute
    fixed:
  File "game/screens.rpy", line 419, in execute
    grid gui.file_slot_cols gui.file_slot_rows:
  File "game/screens.rpy", line 429, in execute
    for i in range(gui.file_slot_cols * gui.file_slot_rows):
  File "game/screens.rpy", line 433, in execute
    button:
  File "game/screens.rpy", line 433, in keywords
    button:
  File "game/screens.rpy", line 434, in <module>
    action FileSave(slot,Confirm = False)
TypeError: __init__() got an unexpected keyword argument 'Confirm'

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Cafe_au_lait 1.0
Tue Apr 18 00:11:09 2023
